version: '3'
services: 
  db_mysql:
    image: mysql 
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=127.0.0.1 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123qwe
      - MYSQL_DATABASE=db_solvy
      - MYSQL_ROOT_PASSWORD=123qwe
    volumes:
      - database_mysql:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - network_api

  api:
    image: robsondcst/api_solvy
    ports: 
      - 3000:3000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    links:
      - db_mysql
    depends_on:
      - db_mysql
    command: sh -c "/wait && ./main"
    environment:
      - WAIT_HOSTS=db_mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    networks:
      - network_api

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  api:
  database_mysql:

networks:
  network_api:
    driver: overlay
